"""add_visual_analytics_fields

Revision ID: 11643bf85de7
Revises: fc6a9534e4ee
Create Date: 2026-01-30 00:40:35.440721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11643bf85de7'
down_revision: Union[str, Sequence[str], None] = 'fc6a9534e4ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chapters', 'summary',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.add_column('summaries', sa.Column('timeline_density', sa.JSON(), nullable=True))
    op.add_column('summaries', sa.Column('word_cloud_data', sa.JSON(), nullable=True))
    op.alter_column('summaries', 'executive_brief',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('summaries', 'executive_brief',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('summaries', 'word_cloud_data')
    op.drop_column('summaries', 'timeline_density')
    op.alter_column('chapters', 'summary',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
