"""add_chat_system_models

Revision ID: 436ddd51bbaf
Revises: 1036a7f6a33f
Create Date: 2026-02-04 01:29:46.619645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '436ddd51bbaf'
down_revision: Union[str, Sequence[str], None] = '1036a7f6a33f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('episode_id', sa.Integer(), nullable=True),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('mode', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_conversations_episode_id'), 'chat_conversations', ['episode_id'], unique=False)
    op.create_index(op.f('ix_chat_conversations_id'), 'chat_conversations', ['id'], unique=False)
    op.create_index(op.f('ix_chat_conversations_user_id'), 'chat_conversations', ['user_id'], unique=False)
    op.create_table('chat_exchanges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('episode_id', sa.Integer(), nullable=True),
    sa.Column('user_message', sa.String(), nullable=True),
    sa.Column('ai_response', sa.String(), nullable=True),
    sa.Column('user_embedding', sa.JSON(), nullable=True),
    sa.Column('response_embedding', sa.JSON(), nullable=True),
    sa.Column('context_snapshot', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_exchanges_episode_id'), 'chat_exchanges', ['episode_id'], unique=False)
    op.create_index(op.f('ix_chat_exchanges_id'), 'chat_exchanges', ['id'], unique=False)
    op.create_index(op.f('ix_chat_exchanges_user_id'), 'chat_exchanges', ['user_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('episode_id', sa.Integer(), nullable=True),
    sa.Column('user_message', sa.String(), nullable=True),
    sa.Column('ai_response', sa.String(), nullable=True),
    sa.Column('context_snapshot', sa.JSON(), nullable=True),
    sa.Column('timestamp_in_episode', sa.Float(), nullable=True),
    sa.Column('user_embedding', sa.JSON(), nullable=True),
    sa.Column('response_embedding', sa.JSON(), nullable=True),
    sa.Column('insights_extracted', sa.JSON(), nullable=True),
    sa.Column('actions_generated', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['chat_conversations.id'], ),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_conversation_id'), 'chat_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_episode_id'), 'chat_messages', ['episode_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    op.create_index(op.f('ix_chat_messages_user_id'), 'chat_messages', ['user_id'], unique=False)
    op.alter_column('entities', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('entities', 'type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_entities_id'), 'entities', ['id'], unique=False)
    op.alter_column('entity_relations', 'episode_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('entity_relations', 'source_entity_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('entity_relations', 'target_entity_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('entity_relations', 'relation_type',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'co_mentioned'::character varying"))
    op.alter_column('entity_relations', 'weight',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.create_index(op.f('ix_entity_relations_id'), 'entity_relations', ['id'], unique=False)
    op.alter_column('episode_entities', 'episode_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('episode_entities', 'entity_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('episode_entities', 'mention_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.create_index(op.f('ix_episode_entities_id'), 'episode_entities', ['id'], unique=False)
    op.drop_constraint(op.f('uq_episodes_user_source_key'), 'episodes', type_='unique')
    op.create_index(op.f('ix_episodes_source_guid'), 'episodes', ['source_guid'], unique=False)
    op.create_index(op.f('ix_episodes_source_url'), 'episodes', ['source_url'], unique=False)
    op.create_foreign_key(None, 'episodes', 'podcasts', ['podcast_id'], ['id'])
    op.create_foreign_key(None, 'episodes', 'users', ['user_id'], ['id'])
    op.create_index(op.f('ix_podcasts_id'), 'podcasts', ['id'], unique=False)
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_podcasts_id'), table_name='podcasts')
    op.drop_constraint(None, 'episodes', type_='foreignkey')
    op.drop_constraint(None, 'episodes', type_='foreignkey')
    op.drop_index(op.f('ix_episodes_source_url'), table_name='episodes')
    op.drop_index(op.f('ix_episodes_source_guid'), table_name='episodes')
    op.create_unique_constraint(op.f('uq_episodes_user_source_key'), 'episodes', ['user_id', 'source_key'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_episode_entities_id'), table_name='episode_entities')
    op.alter_column('episode_entities', 'mention_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('episode_entities', 'entity_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('episode_entities', 'episode_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_entity_relations_id'), table_name='entity_relations')
    op.alter_column('entity_relations', 'weight',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('entity_relations', 'relation_type',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'co_mentioned'::character varying"))
    op.alter_column('entity_relations', 'target_entity_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('entity_relations', 'source_entity_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('entity_relations', 'episode_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_entities_id'), table_name='entities')
    op.alter_column('entities', 'type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('entities', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_chat_messages_user_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_episode_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_conversation_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_chat_exchanges_user_id'), table_name='chat_exchanges')
    op.drop_index(op.f('ix_chat_exchanges_id'), table_name='chat_exchanges')
    op.drop_index(op.f('ix_chat_exchanges_episode_id'), table_name='chat_exchanges')
    op.drop_table('chat_exchanges')
    op.drop_index(op.f('ix_chat_conversations_user_id'), table_name='chat_conversations')
    op.drop_index(op.f('ix_chat_conversations_id'), table_name='chat_conversations')
    op.drop_index(op.f('ix_chat_conversations_episode_id'), table_name='chat_conversations')
    op.drop_table('chat_conversations')
    # ### end Alembic commands ###
