"""Add insight_timeline and topic_transitions to Summary

Revision ID: a7cc19159254
Revises: 11643bf85de7
Create Date: 2026-01-30 01:08:47.415233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7cc19159254'
down_revision: Union[str, Sequence[str], None] = '11643bf85de7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('summaries', sa.Column('insight_timeline', sa.JSON(), nullable=True))
    op.add_column('summaries', sa.Column('topic_transitions', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('summaries', 'topic_transitions')
    op.drop_column('summaries', 'insight_timeline')
    # ### end Alembic commands ###
