"""Add unique constraint to Episode source_url

Revision ID: b8cd4fbef1ac
Revises: a7cc19159254
Create Date: 2026-01-30 01:16:00.811723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8cd4fbef1ac'
down_revision: Union[str, Sequence[str], None] = 'a7cc19159254'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_episodes_source_url'), 'episodes', ['source_url'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_episodes_source_url'), table_name='episodes')
    # ### end Alembic commands ###
